export const GET_TODOS = "GET_TODOS";
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODOS = 'REMOVE_TODOS';
export const SELECT_ALL_TODOS = 'SELECT_ALL_TODOS';
export const UNSELECT_ALL_TODOS = 'UNSELECT_ALL_TODOS';
export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';